### PR TITLE
Update LspDiagnostic colors

### PR DESCRIPTION
**Pull request by mhanberg**
Also sets them to colors that somewhat have semantic meaning

image

### CODE REVIEW

**Comment by sainnhe** [comment]
I don't think it's a good idea to use these colors, they will mess up the code. IMO, all of the virtual text colors should be grey.

Of course this is just my own opinion, you can maintain and use your own fork instead ;)

**Comment by mhanberg** [comment]
Fair enough. The names still need to be updated or else they show up as stock red, yellow, etc.

**Comment by sainnhe** [comment]
> or else they show up as stock red, yellow, etc.

What do you mean by "stock red"? Could you provide a screenshot?

**Comment by mhanberg** [comment]
image

**Comment by mhanberg** [comment]
Sorry, I should have referenced the commit that brought about this change: https://github.com/neovim/neovim/commit/f75be5e9d510d5369c572cf98e78d9480df3b0bb.

**Comment by sainnhe** [comment]
Oh, I see, the upstream has changed the highlight groups.

In fact, recently I received a PR in my another color scheme that adds the new hi groups: https://github.com/sainnhe/gruvbox-material/pull/52

Would you like to help me add them to this color scheme? Since I don't have much time recently.

**Comment by mhanberg** [comment]
This change already updated the highlight groups, i've pushed another commit that sets those back to grey (instead of red/yellow/blue).

I think you if you reopen the PR the commit will show up and you can merge.

**Comment by sainnhe** [comment]
Thank you!

**Pull request merged**
